### PR TITLE
Fix augment path

### LINKED ISSUE #234: augmentPathMap assumes uppercase PATH on windows
On windows, the Path variable may not be uppercase `PATH`, but `Path` and is frequently returned as such by e.g. `getEnvironment` and friends. Using it with `augmentPathMap` may then lead to confusing behavior, where a new key is added and gets ignored.

To make this more robust, on windows, it should:

1. query the existing map for a case-insensitive PATH key
2. use that key to insert the new values

If there are multiple PATH keys, we're screwed. There could be a `normalizePathKeys :: EnvVars -> EnvVars` function that forces it to be upper-case and merges duplicate PATHs?
Sth. like:

```hs
normalizePathKeys  :: EnvVars -> EnvVars
normalizePathKeys = Map.foldrWithKey (\k v m -> case T.toLower k of
                                            "path" -> Map.insert "PATH" v m
                                            _      -> Map.insert k v m) mempty
```

### PR DESCRIPTION
**Pull request by hasufell**
On windows, env vars are generally case-insensitive.
Due to 'type EnvVars = Map Text Text' augmentPathMap
assumes full uppercase "PATH" variable, which may lead
to surprising behavior if the current map
has a variable such as "Path".

This patch folds over the map and inserts any path
key as "PATH" on windows. That also means: if there
are multiple, the "last" one wins. There generally
isn't a sane solution if the input map already
has multiple path keys (how should they be merged,
which order?).

Fixes #234

### CODE REVIEW

File: rio/src/RIO/Process.hs [hunk 1]
```diff
@@ -672,9 +673,21 @@ augmentPath dirs mpath =
...
-     return $ Map.insert "PATH" path origEnv
+     return $ Map.insert "PATH" path normEnv
   where
-    mpath = Map.lookup "PATH" origEnv
+    -- On windows, env vars are case insensitive.
+    -- We pick the "last" PATH variable and ensure
+    -- it's full uppercase.
+    -- See https://github.com/commercialhaskell/rio/issues/234
+    normEnv 
+      | isWindows = Map.foldrWithKey
```
Comment (hasufell) [inline rio/src/RIO/Process.hs:683]: If you fancy the other way, it could also be:

```hs
Map.fromList $ map (first T.toUpper) $ Map.toList tm'
```

which is used `mkProcessContext`.

Factor it out?

Comment (snoyberg) [reply rio/src/RIO/Process.hs:683]: Yeah, that looks better to me. It's easier to understand, and it _might_ be more efficient (though that would need profiling to analyze, I could be wrong).

Factoring out would be great. thanks!

File: rio/src/RIO/Process.hs [hunk 2]
```diff
@@ -287,17 +288,21 @@ mkProcessContext tm' = do
...
     -- Default value for PATHTEXT on Windows versions after Windows XP. (The
     -- documentation of the default at
     -- https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/start
     -- is incomplete.)
     defaultPATHEXT = ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC"
 
 
+-- Fix case insensitivity of the PATH environment variable on Windows,
+-- by forcing all keys full uppercase.
+normalizePathEnv :: EnvVars -> EnvVars
```
Comment (hasufell) [inline rio/src/RIO/Process.hs:300]: Not entirely sure if we need an inline pragma here.

Comment (snoyberg) [reply rio/src/RIO/Process.hs:300]: I think it's reasonable as-is.

**Review by snoyberg — APPROVED** [review]
LGTM. I'll merge/release once CI passes. Thanks!

**Comment by snoyberg** [comment]
Released to Hackage, thanks!

**Comment by snoyberg** [comment]
I'll open a PR against Stack to use this newer version, unless you'd like to open that PR instead.
